export const CRITERIA_TEST_READ_KEY = 'CRITERIA_TEST_READ_KEY'
export const CRITERIA_TEST_READ_REQUEST_KEY = 'CRITERIA_TEST_READ_REQUEST_KEY'
export const CRITERIA_TEST_CLEAR_KEY = 'CRITERIA_TEST_CLEAR_KEY'
