export const AMOUNT_BY_CATEGORY_READ_KEY = 'AMOUNT_BY_CATEGORY_READ_KEY'
export const AMOUNT_BY_CATEGORY_READ_REQUEST_KEY = 'AMOUNT_BY_CATEGORY_READ_REQUEST_KEY'
export const DATA_CHANGES_READ_KEY = 'DATA_CHANGES_READ_KEY'
export const DATA_CHANGES_READ_REQUEST_KEY = 'DATA_CHANGES_READ_REQUEST_KEY'