export const RULES_READ_KEY = 'RULES_READ_KEY'
export const RULES_READ_REQUEST_KEY = 'RULES_READ_KEY'
export const RULES_UPDATE_RULE_REQUEST_KEY = 'RULES_UPDATE_RULE_REQUEST_KEY'
export const RULES_UPDATE_RULE_KEY = 'RULES_UPDATE_RULE_KEY'