export const ROW_ID_SHOW_SET_KEY = 'ROW_ID_SHOW_SET_KEY'
export const ROW_ID_SHOW_CLEAR_KEY = 'ROW_ID_SHOW_CLEAR_KEY'
export const CURRENT_VIEW_NAME_SET = 'CURRENT_VIEW_NAME_SET'
export const CURRENT_VIEW_NAME_CLEAR = 'CURRENT_VIEW_NAME_CLEAR'
